name: CI

on:
  push:
    branches: [ main ]


jobs:
  
  stop:
    name: Server Stop
    runs-on:
      group: Default
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: actions/checkout@v2
        with:
          clean: false

      - name: Stop server (in background)
        run: |
          echo stop
          sudo killall -9 node || true
   
  build:
    name: Build
    runs-on:
      group: Default
    steps:
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: actions/checkout@v2
        with:
          clean: false
          
      - name: Install dependencies
        run: |
          echo install...
          npm ci
  
      - name: build
        run: |
          echo build
          npm run build

      - name: Folder COPY
        run: |
          echo copy
          sudo rm -rf ~/discord/cl-discord-bot || true
          sudo mkdir -p ~/discord/cl-discord-bot
          sudo cp -r ./ ~/discord/cl-discord-bot
          sudo cp -f ~/discord/.env ~/discord/cl-discord-bot/.env


      - name: Run new server (in background)
        run: |
          echo start
          cd ~/discord/cl-discord-bot/
          sudo nohup npm run start </dev/null >/dev/null 2>&1 &