name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - uses: actions/checkout@v2
        with:
          clean: false
        
      - name: Install dependencies
        working-directory: service
        run: |
          npm install


      - name: Stop old server (ignore error)
        run: |
          pm2 delete discord

      - name: Remove old server in ~/soruce (ignore error)
        run: |
          rm -rf /mnt/ssd/apps/cl-discord-bot || true

      - name: Copy new server to ~/soruce
        run: |
          mkdir -p /mnt/ssd/apps/cl-discord-bot
          cp -R ./ /mnt/ssd/apps/cl-discord-bot
          
      - name: build
        run: |
          npm run build
          
      - name: Run new server (in background)
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          cd /mnt/ssd/apps/cl-discord-bot
          pm2 start dist/index.js
