name: CI

on:
  push:
    branches: [ main ]

jobs:
  install:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: npm ci

  build:
    steps:
    - uses: actions/checkout@v2
    - run: npm run build,
  
  start:
    steps:
    - uses: actions/checkout@v2
    - run: pm2 dist
