name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
	
jobs:
  build:
    runs-on: self-hosted
	
    steps:
    - uses: actions/checkout@v2

    - name: CI
    - run: npm ci

    - name: Build
    - run: npm run build

    - name: Start
    - run: npm run start
