name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: actions/checkout@v2
        with:
          clean: false
        
      - name: Install dependencies
        run: |
          echo install...
          npm install

      - name: build
        run: |
          echo build
          npm run build
          sudo cp ~/discord/.env ./env

      - name: Remove old server in ~/soruce (ignore error)
        run: |
          echo remove
          sudo rm -rf ~/discord/cl-discord-bot || true

      - name: Copy new server to ~/soruce
        run: |
          echo copy...
          sudo mkdir -p ~/discord/cl-discord-bot
          sudo cp -R ./ ~/discord/cl-discord-bot
          
          
      
          
      - name: Run new server (in background)
        env:
          RUNNER_TRACKING_ID: ""
        run: |
          echo start
          cd ~/discord/cl-discord-bot
          sudo npx pm2 start dist/index.js --name discord 
