name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - run: |
        npm ci,
        npm run build,
        pm2 start dist/index.js